anchore/vunnel

- schema/provider-workspace-state/schema-1.0.0.json
- tests/conftest.py
- tests/unit/test_workspace.py
The current json schema for the workplace state was not under test and the schema was incorrect relative to the data shape that was actually being output by vunnel. This PR fixes the schema to reflect the existing data shape (which is why this mutates the existing 1.0.0 schema instead of bumping it).
> Fix workspace schema to be correct relative to actual 1.0 datashape

- tests/quality/config.yaml
- tests/quality/configure.py
Currently it isn't possible to install grype-db from a fork. This PR refactors the grype-db install code to be a little more modular and adds install capability for forks and local user paths (e.g. `file://~/code/grype-db`).
> Fix grype-db install within quality gate

- src/vunnel/providers/ubuntu/git.py
- src/vunnel/providers/ubuntu/parser.py
If the directory doesn't exist, there is no need to execute the `git rev-parse --is-inside-work-tree` command, we can just return false from the check command.  This silences an exception being thrown and logged on every initial run, thereby reducing support questions.  
Also adds a bit more info-level logging for the ubuntu provider
> fix: avoid ubuntu git repo check exception on missing directory

- tests/quality/configure.py
Currently only the standard provider globs are being considered for test detection of the quality gate, this PR fixes this behavior to additional consider the `additional-trigger-globs` configuration value.
> Fix selecting providers to test by additional trigger globs

- src/vunnel/providers/rhel/parser.py
When a full sync of the RHEL CVE data is triggered, there is no log output for a very long time at info level, so this at least outputs a row for each page of data processed, which should indicate that things are progressing
> chore: more info logging for rhel long operations

- .github/scripts/update-dev-db.sh
- src/vunnel/providers/ubuntu/parser.py
- tests/unit/providers/ubuntu/test_ubuntu.py
The Ubuntu CVE Tracker repo made updates to the labelling used to indicate end of life so that unfixed vulnerabilities for older distros were no longer getting detected properly.  This updates the regex used to catch more of the existing (and additional historical labels) that were being missed.  This will require a full purge of existing workspace in order to pick up these historical vulns again
> fix: detect updated ubuntu eol labels

- src/vunnel/providers/mariner/parser.py
- src/vunnel/providers/sles/parser.py
- src/vunnel/utils/vulnerability.py
- tests/unit/providers/mariner/test_mariner.py
- tests/unit/providers/sles/test_sles.py
Update dataclass representations for AdvisorySummary and VendorAdvisory so that Module and VendorAdvisory (both optional) could be added to the FixedIn dataclass specification.
> chore: update AdvisorySummary and VendorAdvisory with FixedIn info

- src/vunnel/providers/ubuntu/parser.py
Adds the necessary mappings for Ubuntu 23.04 (Lunar Lobster), and Ubuntu 23.10 (Mantic Minotaur)
> feat: add mappings for ubuntu 23.04, 23.10

- src/vunnel/providers/ubuntu/__init__.py
This ensures that existing workspace state will not be considered so that all of history is reprocessed to pick up the necessary changes from https://github.com/anchore/vunnel/pull/222
> feat: bump ubuntu provider to v2 to ensure rebuild from clean workspace after upstream data changes

- src/vunnel/provider.py
- src/vunnel/providers/alpine/__init__.py
- src/vunnel/providers/amazon/__init__.py
- src/vunnel/providers/chainguard/__init__.py
- src/vunnel/providers/debian/__init__.py
- src/vunnel/providers/github/__init__.py
- src/vunnel/providers/mariner/__init__.py
- src/vunnel/providers/nvd/__init__.py
- src/vunnel/providers/oracle/__init__.py
- src/vunnel/providers/rhel/__init__.py
- src/vunnel/providers/sles/__init__.py
- src/vunnel/providers/wolfi/__init__.py
- src/vunnel/result.py
- tests/unit/test_result.py
When using the sqlite writer, preserve the prior results as long as possible by writing the new results to a temp file and then renaming it after everything is successful.
> feat: preserve prior results longer with sqlite writer

- src/vunnel/providers/alpine/parser.py
- src/vunnel/providers/mariner/parser.py
Adds additional retry with backoff logic on url fetches for the `alpine` and `mariner` providers
There was already a retry on parsing the alpine security db for a specific release, but there wasn't a retry on fetching the landing page to parse the release-specific links from.
> fix: add retry on alpine and mariner url fetches

- src/vunnel/providers/mariner/__init__.py
- src/vunnel/providers/mariner/parser.py
- tests/unit/cli/test_cli.py
- tests/unit/providers/mariner/test-fixtures/mariner-truncated-2.0-oval.xml
Fixes https://github.com/anchore/grype/issues/1393
Fix Mariner provider to stop including CVEs that are "Not Applicable." Additionally, fix the data retention to regenerate the Mariner database, rather than appending to it, since we are downloading entire OVAL files every time.
> Fix grype1393

- src/vunnel/providers/rhel/__init__.py
- src/vunnel/providers/rhel/parser.py
- tests/unit/cli/test_cli.py
- tests/unit/providers/rhel/test_rhel.py
Sets the result store policy for the `rhel` provider to `DELETE_BEFORE_WRITE`.  There shouldn't be a reason for the rhel provider to need to accumulate result state between runs as it always iterates over the full input set.  This will address an issue where vulnerabilities marked as `not-affected` don't get dropped from the results.
Fixes #252
> fix: don't accumulate result state with rhel provider

- src/vunnel/providers/rhel/parser.py
- tests/unit/providers/rhel/test_rhel.py
Out of support entries from the RHEL provider should always be included as affected if there is no other fixed-in or affected information from other releases
> fix: always include rhel out of support entries when no other fix info available for any other releases

- Makefile
Previous crane version say installation errors when installed with go 1.20.7:
```
$ go version
go version go1.20.7 darwin/arm64
$ make bootstrap
mkdir -p ./.tmp
curl -sSfL https://raw.githubusercontent.com/anchore/chronicle/main/install.sh | sh -s -- -b ./.tmp/ v0.6.0
anchore/chronicle info checking GitHub for tag 'v0.6.0'
anchore/chronicle info found version: 0.6.0 for v0.6.0/Darwin/all
anchore/chronicle info installed ./.tmp//chronicle
GOBIN="/Users/willmurphy/work/vunnel-clean/.tmp" go install github.com/charmbracelet/glow@v1.4.1
GOBIN="/Users/willmurphy/work/vunnel-clean/.tmp" go install github.com/google/go-containerregistry/cmd/crane@v0.12.1
../../go/pkg/mod/golang.org/x/sys@v0.1.0/unix/ioctl.go:11:2: "os" imported and not used
make: *** [bootstrap] Error 1
```
> chore: bump crane

- src/vunnel/providers/amazon/parser.py
- tests/unit/providers/amazon/test_amazon.py
Closes #254 
adding a description for vulnerabilities from amazon provider
> Add description to amazon provider

- tests/unit/providers/debian/test_debian.py
The provider is intentionally resilient to malformed records, and implements this resilience by logging and continuing on when any exception is thrown. However, this prevents the unit tests from many errors in the implementation of the provider. Therefore, spy on the provider and fail unit tests if it is logging exceptions.
Part of https://github.com/anchore/vunnel/issues/309, but doesn't resolve it.
> chore: improve unit tests in debian provider

- README.md
I found centos being listed in the readme but not in my output a bit confusing, so updated the list to match what I got today.
> Update vunnel list output in README.md

- .github/workflows/nightly-quality-gate.yaml
- .github/workflows/pr-quality-gate.yaml
There are a couple problems:
- The gate logic was explicitly checking if there was a failure instead of checking explicitly for success (and failing otherwise)
- The notification was on the PR gate, not the nightly gate
> Fix nightly quality gate notification

- Makefile
The grype main file moved into a subdirectory, and this command hadn't been updated.
With this change, `make dev providers=amazon` builds grype; without this change it printed an error about building grype.
> chore: fix "make build-grype"

- tests/quality/config.yaml
It looks like there is a coupling of the github provider and the alpine/wolfi providers, which is incorrect (thus removed). I've also cleaned up the configuration to use underscores vs dashes more consistently (use underscores all the time).
> Remove incorrect quality gate configuration

- tests/quality/config.yaml
- tests/quality/configure.py
Reverts #354 and adds additional quality gate triggers, so if the quality gate code changes then all providers must be tested.
Investigating this also lead to a conclusion about how we measure results, captured in https://github.com/anchore/vunnel/issues/359
> Revert github namespace selection

- src/vunnel/providers/rhel/oval_parser.py
This way, changes to this file will still get linted.
See #310
> chore: remove file noqa from rhel oval parser

- src/vunnel/providers/nvd/api.py
- src/vunnel/providers/nvd/manager.py
> chore: remove file-scoped noqa from NVD

- .github/actions/quality-gate/action.yaml
- .gitignore
When there is a quality gate failure it tends to take a lot of time to reproduce the state in CI locally to then go and introduce more labels or dive deeper into the raw data. With this PR the `.yardstick` and `.yardstick.yaml` data is captured as a CI artifact automatically on failure with instructions on how to use it:
Example run: https://github.com/anchore/vunnel/actions/runs/6657772557
Fixes #360
> Store quality gate state on failure

- src/vunnel/utils/oval_parser.py
- tests/quality/config.yaml
This way, the set of lints suppressed in the file cannot grow unnoticed.
See #310
> chore: remove file noqa for utils oval parser

- src/vunnel/providers/alpine/parser.py
This way, the set of suppressed lints on the parser will not grow.
See #310
> chore: Remove file noqa on alpine parser

- src/vunnel/providers/sles/parser.py
This way, the set of suppressed lints in the file will not grow.
See #310.
> chore: remove file noqa on SLES parser

- src/vunnel/utils/oval_v2.py
Suppress lints that would require changing control flow. Otherwise, accept some automatic fixes.
See #310
> chore: remove file noqa from utils OVAL V2 parser

- .github/workflows/nightly-quality-gate.yaml
This should help with non-cve IDs that can't easily be filtered from the results based on year (GHSAs) that cause false-positive quality gate failures. Comparing with data from 22 hours earlier isn't an apples-to-apples comparison, this change gets that to within an hour 🤞 .
> Move nightly quality gate to be roughly after the latest DB build

- src/vunnel/providers/oracle/parser.py
- tests/unit/providers/oracle/test_oracle.py
Use the new http get wrapper introduced in #376 in the oracle provider.
See also #310.
> refactor: use new http get wrapper in oracle provider

- tests/quality/configure.py
Previously, if "git diff" included the yardstick dependency declaration in one of the context/unchanged lines, configure.py would request running the quality gate on every provider. Fix this false positive by only considering lines with changes in them in the output.
Basically, [this check](https://github.com/anchore/vunnel/pull/374/files#diff-70418a48df4fa132049398d4aba7e5c863decf012a8242eebf9b8adc888f59e7R342) could false positive, as evident in https://github.com/anchore/vunnel/pull/387 trying to run all the providers even though it doesn't change anything that should necessitate that.
> chore: fix false positive in detecting that yardstick changed

- src/vunnel/providers/nvd/__init__.py
Although providing an API key for the NVD provider is highly encouraged, it is not required and is not set in all of our environments.
> fix: NVD api key should not be required

- src/vunnel/providers/wolfi/parser.py
- tests/unit/providers/chainguard/test_chainguard.py
- tests/unit/providers/wolfi/test_wolfi.py
Also change chainguard unit tests, since chainguard uses the wolfi provider.
> refactor: http.get wrapper in wolfi provider

- src/vunnel/providers/rhel/parser.py
Prior to this change, every single record without a CVSS V3 score will emit a ValueError on info log level.  
```
File "/usr/local/lib/python3.11/site-packages/vunnel/providers/rhel/parser.py", line 815, in __init__
2023-11-23T01:31:16.9105321Z [0073]  INFO rhel: raise ValueError("vector_string and base_score must be valid")
2023-11-23T01:31:16.9106520Z [0073]  INFO rhel: ValueError: vector_string and base_score must be valid
2023-11-23T01:31:16.9261917Z [0073]  INFO rhel: [0munable to make cvss3, defaulting to None[0m
2023-11-23T01:31:16.9262912Z [0073]  INFO rhel: Traceback (most recent call last):
2023-11-23T01:31:16.9264548Z [0073]  INFO rhel: File "/usr/local/lib/python3.11/site-packages/vunnel/providers/rhel/parser.py", line 682, in _parse_cve
2023-11-23T01:31:16.9265594Z [0073] …
```
> chore(rhel): improved handling CVSS V3 parsing

- src/vunnel/utils/oval_v2.py
Previously this would log an exception stacktrace for parsing any `criteria` or `criterion` element that didn't have a `comment` attribute
```
[INFO ] downloading OVAL file for SLES 12 from https://ftp.suse.com/pub/projects/security/oval/suse.linux.enterprise.server.12.xml.gz
[DEBUG] http GET https://ftp.suse.com/pub/projects/security/oval/suse.linux.enterprise.server.12.xml.gz
[INFO ] parsing ./data/sles/input/source/oval/suse-linux-enterprise-server-12.xml.gz
[ERROR] returning results early due to exception in _parse_sub_group
Traceback (most recent call last):
File "/Users/weston/github/anchore/vunnel/src/vunnel/utils/oval_v2.py", line 190, in _parse_group
test_ids = VulnerabilityParser._parse_sub_group(criteria_element[1], config, config.artifact_regex)
File …
```
> fix: improve oval v2 parsing to prevent unnecessary exceptions

- .github/workflows/dependabot-auto-merge.yaml
Otherwise, because auto-merge was previously enabled, an experimental commit pushed to a dependabot branch could end up on main if it happened to pass CI.
> Update dependabot-auto-merge to cancel itself on human push

- .github/workflows/dependabot-auto-merge.yaml
Otherwise, the workflow won't run on events where another user modified a dependabot PR.
> Check PR author login, instead of actor

- schema/vulnerability/nvd/README.md
- schema/vulnerability/nvd/cvss/README.md
- schema/vulnerability/nvd/cvss/schema-v2.0.json
- schema/vulnerability/nvd/cvss/schema-v3.0.json
- schema/vulnerability/nvd/cvss/schema-v3.1.json
- tests/conftest.py
This adds all schemas that are referenced by URL within other already-captured schemas to a location within the repo. Additionally, the test fixture responsible for schema validation has been updated to manually map URLs to paths within the repo to use such that no network calls are used. Without this update you tend to see [flaky behavior in CI](https://github.com/anchore/vunnel/actions/runs/7324485690/job/19948100788):
```
tests/unit/providers/nvd/test_nvd.py:52: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
tests/conftest.py:59: in result_schemas_valid
jsonschema.validate(instance=envelope["item"], schema=schema_dict)
.tox/py310/lib/python3.10/site-packages/jsonschema/validators.py:1306: in validate
error = …
```
> Load all schema url refs for offline validation

- src/vunnel/providers/rhel/parser.py
The RHEL provider currently only gathers security data for Red Hat Enterprise Linux packages, so filtering by product up front when retrieving the applicable CVE's will be more efficient.
> chore(rhel): filter by product name when retrieving summary cves 

- src/vunnel/providers/debian/parser.py
The Debian feed contains per-package urgency for CVEs, which Vunnel translates into per-package severity, and the collapses into a single per-CVE serverity by having the most severe severity win. However, unknown severities always lose the comparison. This means that the particular CVE here, CVE-2023-44487, which has a single negligible package and a bunch of unknowns, is treated as negligible severity for every package, which is incorrect. Hard-code it to unknown severity (so that Grype-DB will take severity from NVD's data), while we figure out what schema changes and logic changes are needed put in a lasting fix.
See https://github.com/anchore/grype-db/issues/108#issuecomment-1796301073 for more info
```
$ make dev providers="debian nvd"
$ make update-db
$ sqlite3 --header --column …
```
> hack: hard-code severity for debian CVE-2023-44487

- .github/workflows/dependabot-automation.yaml
When dependabot PRs are automatically merged, the resulting commit doesn't run workflows on main if the default GitHub token is used. Rather than generate a more potent token, or live with some commits not running workflows on main, scale back dependabot automation to only approve the PRs but not merge them. This still reduces toil by saving several clicks in the UI.
Copied from anchore/grype-db#222
> chore: change dependabot to auto-approve only

- schema/vulnerability/osv/README.md
- schema/vulnerability/osv/schema-1.6.1.json
- src/vunnel/schema.py
As described at https://github.com/anchore/grype/issues/1609, Bitnami is providing vulnerability matching data for their containers via the [Bitnami Vulnerability Database repository](https://github.com/bitnami/vulndb).
This database uses the [Open Source Vulnerability format](https://ossf.github.io/osv-schema) (AKA OSV) and it's currently part of the [aggregated OSV vulnerability database](https://osv.dev/list).
As a first step towards consuming this CVE feed and improve Grype scanning capabilities on Bitnami containers, this PR adds support for the OSV schema to vunnel.
> feat: add support for OSV schema

- poetry.lock
- pyproject.toml
To bring in the ALAS filtering fixes from https://github.com/anchore/yardstick/pull/239
> chore(deps-dev): bump yardstick to v0.9.2

- poetry.lock
- pyproject.toml
It seems like python-future is no longer needed here and according to the [1.0.0 release notes](https://github.com/PythonCharmers/python-future/releases/tag/v1.0.0)
> The new version number of 1.0.0 indicates that the python-future project, like
Python 2, is now done.
> feat(deps): drop python-future

- src/vunnel/providers/rhel/oval_parser.py
This removes the sha256 check from the oval provider so that users will always skip the checksum matching when parsing the following oval data.
It was previously used as a method to skip the download if there was no change. We now opt to always download and remove the complexity based on the below manifest not always having a sha to check against
https://www.redhat.com/security/data/oval/v2/PULP_MANIFEST
> fix: remove sha256 verification for oval parser

- poetry.lock
- src/vunnel/providers/nvd/__init__.py
- src/vunnel/providers/nvd/manager.py
- src/vunnel/providers/nvd/overrides.py
- src/vunnel/result.py
- src/vunnel/utils/oval_v2.py
- tests/unit/cli/test-fixtures/full.yaml
- tests/unit/cli/test_cli.py
- tests/unit/cli/test_config.py
- tests/unit/providers/nvd/test_manager.py
- tests/unit/providers/nvd/test_nvd.py
- tests/unit/providers/nvd/test_overrides.py
Allows specifying a URL to a tar.gz with NVD overrides data.  This initial version solely supports overriding the `configurations` section of the NVD record and if an override record exists with the CPE configurations section set, it will always override the NVD `configurations` section.
This also integrates the changes to split the NVD data into a separate input database as well as the work done to download from a tar.gz
> Allows overriding CPE configurations on NVD records

- src/vunnel/providers/nvd/manager.py
- tests/unit/providers/nvd/test_manager.py
This fixes an issue where fetching the record to apply the override would always fail to find the record because it was written with an uppercase key but fetched with a lowercase key.
> Input sqlite db should follow lowercase identifier convention

- src/vunnel/result.py
- src/vunnel/workspace.py
Replace instances of `os.rename` with `shutil.move` to handle the possibility of the destination being a different filesystem.  If the source and destination are on the same filesystem, `os.rename` is used per https://docs.python.org/3.11/library/shutil.html#shutil.move
> fix: os.rename -> shutil.move

- tests/quality/config.yaml
Since SLES 15.6 is out, this PR updates the quality gate check to include it as an expected namespace.
Additionally updates vulnerability match labels to account for failure.
> Add SLES 15.6 to quality gate

- src/vunnel/provider.py
- tests/unit/test_provider.py
When using the results import approach @westonsteimel noticed that the workspace metadata timestamp was being (erroneously) updated:
The hosted metadata:
```json
{
"provider": "amazon",
"timestamp": "2024-04-29T13:06:00.992247+00:00",
"stale": true,
...
}
```
After running vunnel and importing the hosted results archive:
```json
{
"provider": "amazon",
"timestamp": "2024-05-01T01:30:31.951204+00:00",
"stale": true,
...
}
```
This is because when calling `provider.update()` the metadata is overwritten with a new timestamp value. This PR fixes this such that the timestamp of the import is persisted/honored (instead of updating the timestamp to time-of-import).
> Keep original import timestamp on results archive import

- src/vunnel/providers/amazon/__init__.py
- src/vunnel/providers/amazon/parser.py
- tests/unit/cli/test-fixtures/full.yaml
- tests/unit/cli/test_cli.py
- tests/unit/cli/test_config.py
- tests/unit/providers/amazon/test_amazon.py
It seems that there are some irregularities in the amazon vulnerability data, where the RSS feed that lists ALAS records is not synced with the accompanying HTML files with the advisory details. When this happens, on the first failed request for a non-existing ALAS record we get a HTTP 403 response code and the provider bails with error. This has been happening intermittently for weeks and is most prone to happen when there is no pre-existing state for a given record (as with the vunnel quality gate, and less likely with nightly grype-db builds).
This PR changes the behavior to allow for a limited number of HTTP 403s across all requests for ALAS HTML files, printing the summary of failures at the end of processing:
```bash
[WARNING] failed to fetch 9 ALAS entries due to HTTP 403 response …
```
> Allow for missing ALAS files in Amazon provider

- src/vunnel/cli/config.py
- src/vunnel/provider.py
- tests/unit/cli/test_cli.py
this commit updates the provider date when vunnel is importing results and an options to skip date checks
> fix: update vunnel provider date and option to skip listing check

- src/vunnel/providers/ubuntu/parser.py
The codename for Ubuntu 24.10 is `Oracular Oriole` per https://wiki.ubuntu.com/Releases, so this gets the mapping to version in place well in advance
> feat: add ubuntu 24.10 codename to version mapping

- .github/actions/bootstrap/action.yaml
- .github/workflows/validations.yaml
- tox.ini
I believe that previously there was some incompatibility with mashumaro and python 3.12; however, that seems to have been addressed with the latest version in https://github.com/anchore/vunnel/commit/418701a5c260cc6d97631a9f8f5b92c789f9075d, so this adds validations for python 3.12
> chore: validations for python 3.12

- src/vunnel/providers/debian/parser.py
https://github.com/anchore/vunnel/pull/622 added some additional cves to ignore the debian provided priority; however, most of the applied to records from debian 10 which are now captured in the legacy storage and don't follow the normal processing, so this relocates the logic to a place which will also process loegacy entries.
> hack: move debian priority ignore to account for legacy records

- pyproject.toml
- src/vunnel/cli/cli.py
- src/vunnel/provider.py
- src/vunnel/providers/amazon/parser.py
- src/vunnel/providers/github/parser.py
- src/vunnel/providers/nvd/manager.py
- src/vunnel/providers/nvd/overrides.py
- src/vunnel/providers/oracle/parser.py
- src/vunnel/providers/rhel/oval_parser.py
- src/vunnel/providers/rhel/parser.py
- src/vunnel/providers/ubuntu/git.py
- src/vunnel/providers/ubuntu/parser.py
- src/vunnel/providers/wolfi/parser.py
- src/vunnel/schema.py
- src/vunnel/utils/oval_parser.py
Previously, RUF100 was disabled, meaning that ruff would pass even if there were noqa comments that were not needed. Remove unneeded noqa comments and enable this lint. This is important because unneeded noqa comments leave the door open for re-introducing linter errors that are previously fixed.
Aside from the pyproject.toml change, this diff was generated by running:
ruff check . --extend-select RUF100 --fix
> chore: remove unneeded noqa, enable lint for same

- src/vunnel/providers/sles/parser.py
- tests/unit/providers/sles/test-fixtures/snapshots/sles:15/cve-2010-1323.json
- tests/unit/providers/sles/test-fixtures/suse_truncated.xml
- tests/unit/providers/sles/test_sles.py
Fix https://github.com/anchore/grype-db/issues/344, some package where missing from sles database because of an error in the parser.
The code avoid to crush old packages list when we have multiple criteria for the same os version. 
Thanks to @spiffcs and @willmurphyscode for the help
> fix: grype_db #344 missing CVE/Package associations

- .gitmodules
The branch it previously pointed at has been removed in the remote, which messes updating submodules from remote because git can't find the remote branch to update from.
It looks to me like anchore/vunnel#597 needed this until anchore/vulnerability-match-labels#136 was merged, but I don't think it needs it any more.
Without change:
``` sh
$ git clone --recurse-submodules git@github.com:anchore/vunnel
$ cd vunnel
$ git submodule update --remote --recursive
fatal: Unable to find refs/remotes/origin/ubuntu-label-updates revision in submodule path 'tests/quality/vulnerability-match-labels'
```
With change:
``` sh
$ git clone --recurse-submodules git@github.com:anchore/vunnel -b chore-back-to-main-vulns
$ cd vunnel
$ git submodule update --remote --recursive # succeeds!
```
> chore: switch submodule back to main branch

- .github/workflows/validations.yaml
- src/vunnel/providers/mariner/__init__.py
- src/vunnel/providers/mariner/generate_models.py
- src/vunnel/providers/mariner/model/generated.py
- src/vunnel/providers/mariner/parser.py
- tests/quality/config.yaml
- tests/unit/cli/test_cli.py
- tests/unit/providers/mariner/test-fixtures/azure-linux-truncated-3.0-oval.xml
- tests/unit/providers/mariner/test_mariner.py
Includes re-generating models for parsing OVAL XML.
See also https://github.com/anchore/grype/pull/1848
> feat: add azurelinux3 vuln feed

- tests/quality/config.yaml
Now that vulnerability data is being published for Ubuntu 24.10, we need to add the vulnerability namespace to the expected namespace validation
> test: add validation for ubuntu 24.10 namespace

- .gitignore
- .pre-commit-config.yaml
- schema/provider-workspace-state/schema-1.0.3.json
- src/vunnel/schema.py
- src/vunnel/workspace.py
This adds vunnel version information to workspace output, so we know which version of vunnel did the processing of the upstream data. This is related to [grype DB v6 work](https://github.com/orgs/anchore/projects/22/views/23?pane=issue&itemId=80129876&issue=anchore%7Cgrype%7C2125) so that we have more detail on a provider-level on how the data was handled upstream.
> Add processor to workspace state

- .github/workflows/release.yaml
Since the NVD API is down/degraded, we are currently blocked from releasing (since our quality gate depends on testing against our upstream providers). This PR adds a break-glass feature into the release pipeline to bypass this check in case of emergencies.
> Add switch to bypass quality gate

- tests/quality/config.yaml
Fixes https://github.com/anchore/vunnel/actions/runs/12193244522/job/34022256218#step:4:2245
> chore: add alpine:3.21 to expected namespaces

- src/vunnel/providers/ubuntu/parser.py
The codename for Ubuntu 25.04 is `Plucky Puffin` per https://wiki.ubuntu.com/Releases, so this gets the mapping to version in place. This Ubuntu release is out on 17th April.
> feat: add ubuntu 25.04 codename to version mapping

- src/vunnel/provider.py
- src/vunnel/providers/alpine/parser.py
- src/vunnel/providers/amazon/parser.py
- src/vunnel/providers/debian/parser.py
- src/vunnel/providers/kev/manager.py
- src/vunnel/providers/mariner/parser.py
- src/vunnel/providers/nvd/api.py
- src/vunnel/providers/nvd/overrides.py
- src/vunnel/providers/oracle/parser.py
- src/vunnel/providers/rhel/csaf_client.py
- src/vunnel/providers/rhel/parser.py
- src/vunnel/providers/sles/parser.py
- src/vunnel/providers/wolfi/parser.py
- src/vunnel/utils/http_wrapper.py
- tests/conftest.py
- tests/unit/providers/amazon/test_amazon.py
- tests/unit/providers/kev/test_kev.py
- tests/unit/providers/nvd/test_api.py
- tests/unit/providers/rhel/test_csaf_client.py
- tests/unit/utils/test_http_wrapper.py
Previously, vunnel.utils.http was shadowing standard lib http, which led to some weird behavior if a library expected to use the standard lib http but the symbol was shadowed.
> chore: rename http to http_wrapper

- schema/vulnerability/osv/schema-1.7.0.json
- src/vunnel/cli/config.py
- src/vunnel/providers/__init__.py
- src/vunnel/providers/alma/__init__.py
- src/vunnel/providers/alma/git.py
- src/vunnel/providers/alma/parser.py
- tests/unit/cli/test_cli.py
- tests/unit/providers/alma/test-fixtures/osv-database/advisories/almalinux8/ALBA-2021:4378.json
- tests/unit/providers/alma/test-fixtures/osv-database/advisories/almalinux8/ALSA-2023:4520.json
- tests/unit/providers/alma/test-fixtures/osv-database/advisories/almalinux9/ALSA-2022:8194.json
- tests/unit/providers/alma/test-fixtures/osv-database/advisories/almalinux9/ALSA-2024:2433.json
- tests/unit/providers/alma/test_alma.py
- tests/unit/test_provider.py
This creates a new Vunnel provider that pulls AlmaLinux's OSV data from https://github.com/AlmaLinux/osv-database.
It will make use of the grype-db OSV transform currently in progress in anchore/grype-db#217.
How to interpret this data once it's in Grype's database is another question. For example, is this data intended to supplement or replace upstream data from RedHat? I think we can discuss those questions during or even after review of this PR, because this PR just makes the data available to grype db without any real interpretation.
The only caveat on the data so far is that, AFAICT, Alma's repo does not say which version of the OSV spec will be emitted. Because the code that generates the repo depends on the latest version of the `osv` PyPI package, I've assumed that they are …
> feat: alma linux OSV provider

- src/vunnel/cli/cli.py
- src/vunnel/provider.py
- src/vunnel/providers/rocky/__init__.py
- src/vunnel/providers/rocky/client.py
- src/vunnel/providers/rocky/parser.py
- tests/unit/cli/test_cli.py
- tests/unit/providers/rocky/test_rocky.py
This adds the ability to skip downloading to the CLI, so that users can run "vunnel run <provider> --skip-download". This is useful when working on a provider with a slow download step.
Currently, only Rocky Linux provider supports this. Other providers passed this flag will log a warning and then ignore the flag.
Right now:
* running with `--skip-download` on rocky provider works and skips downloads
* Running with `--skip-download` on rocky provider when there's no input will raise an error
* Running other providers with `--skip-download` will log a warning but carry on
Outputs:
```
❯ vunnel -v run rocky --skip-download
[DEBUG] discovered plugins: 0
[INFO ] running rocky provider
... snip ...
[INFO ] Skipping download of Rocky Linux advisories
[INFO ] wrote 1578 entries
❯ vunnel -v run …
```
> feat: add skip download CLI option

- src/vunnel/providers/github/parser.py
Adds the GitHub-actions ecosystem to the supported ecosystems list, mapping to the appropriate syft package type.
Partially addresses https://github.com/anchore/grype/issues/2530
> Support the github actions ecosystem within the GitHub provider

- .github/workflows/release.yaml
Currently, the release workflow asks for manual deployment before beginning, and again before pypi release. The second request for manual review is unintentional; this commit removes it.
> chore: remove redundant release check

- .github/workflows/release.yaml
This reverts commit 1f2fac203aa199e61a5c0908a56c9f3c000deada. The first release after that commit was made failed with a permissions error in the step that was changed. Therefore, reverting the commit on the assumption that it was to blame. This will have the side effect of causing there to once again be two manual confirmation steps in a vunnel release, but this is preferable to partially executed releases.
Here's the failure that the reverted commit seems to have caused: https://github.com/anchore/vunnel/actions/runs/15567277745/job/43834459062#step:4:600
> Revert "chore: remove redundant release check (#820)"

- pyproject.toml
- uv.lock
update python constraint to allow 3.13.x
fixes #809
relates to 
- https://github.com/anchore/vunnel/pull/762
- https://github.com/Homebrew/homebrew-core/pull/227476
> fix: update python constraint to allow 3.13.x

- src/vunnel/providers/rhel/parser.py
- src/vunnel/utils/csaf_types.py
- tests/unit/providers/rhel/test-fixtures/snapshots/rhel:8.6+eus/cve-2023-4863.json
- tests/unit/providers/rhel/test-fixtures/snapshots/rhel:8.6+eus/cve-2023-5129.json
- tests/unit/providers/rhel/test-fixtures/snapshots/rhel:8.6+eus/cve-2023-5217.json
- tests/unit/providers/rhel/test-fixtures/snapshots/rhel:9.0+eus/cve-2023-4863.json
- tests/unit/providers/rhel/test-fixtures/snapshots/rhel:9.0+eus/cve-2023-5129.json
- tests/unit/providers/rhel/test-fixtures/snapshots/rhel:9.0+eus/cve-2023-5217.json
- tests/unit/providers/rhel/test_rhel.py
This PR adds the ability for vunnel to emit vulnerability records that indicate a "channel", embedded in the OS name (e.g. `rhel:8` has no channel vs `rhel:8+eus` has an `eus` channel). This enables grype, when anchore/grype#2782 and anchore/grype#2787 are merged, to be able to reason about disclosures from one source and fixes from another source.  
This partially addresses anchore/grype#2446.
> Add support for RedHat EUS data

- src/vunnel/providers/rhel/__init__.py
- src/vunnel/providers/rhel/parser.py
- src/vunnel/utils/__init__.py
- tests/unit/cli/test_cli.py
- tests/unit/providers/rhel/test-fixtures/csaf/input/cve/min_pages/1.json
- tests/unit/providers/rhel/test_parser.py
- tests/unit/providers/rhel/test_rhel.py
There was an extended period of time where the hydra API was returning 403s for https://access.redhat.com/hydra/rest/securitydata/cve.json, causing the provider to fail.... however, this is an unauthenticated endpoint. We already have previous hydra data in the input workspace, this PR adds a new `ignore_hydra_errors` configuration to ignore such errors and use cached data instead.
> Add configuration to bypass RHEL hydra API failures

- tests/quality/config.yaml
This PR is basically to prove that https://github.com/anchore/grype/pull/2889 fixes the quality gate failures we're seeing on main.
> fix: bump match labels to pull in alpine fix

- src/vunnel/providers/alpine/__init__.py
- src/vunnel/providers/alpine/parser.py
- tests/unit/cli/test_cli.py
- tests/unit/providers/alpine/test-fixtures/snapshots/3.15/cve-2018-1071.json
- tests/unit/providers/alpine/test-fixtures/snapshots/3.15/cve-2018-1083.json
- tests/unit/providers/alpine/test-fixtures/snapshots/3.15/cve-2018-25032.json
- tests/unit/providers/alpine/test-fixtures/snapshots/3.15/cve-2019-11922.json
- tests/unit/providers/alpine/test-fixtures/snapshots/3.15/cve-2019-13132.json
- tests/unit/providers/alpine/test-fixtures/snapshots/3.15/cve-2019-20044.json
- tests/unit/providers/alpine/test-fixtures/snapshots/3.15/cve-2019-6250.json
- tests/unit/providers/alpine/test-fixtures/snapshots/3.15/cve-2019-9210.json
- tests/unit/providers/alpine/test-fixtures/snapshots/3.15/cve-2020-14929.json
- tests/unit/providers/alpine/test-fixtures/snapshots/3.15/cve-2020-15166.json
- tests/unit/providers/alpine/test-fixtures/snapshots/3.15/cve-2021-24031.json
- tests/unit/providers/alpine/test-fixtures/snapshots/3.15/cve-2021-24032.json
- tests/unit/providers/alpine/test-fixtures/snapshots/3.15/cve-2021-38370.json
- tests/unit/providers/alpine/test-fixtures/snapshots/3.15/cve-2021-45444.json
- tests/unit/providers/alpine/test-fixtures/snapshots/3.15/cve-2022-1271.json
- tests/unit/providers/alpine/test-fixtures/snapshots/3.15/cve-2022-37434.json
- tests/unit/providers/alpine/test_alpine.py
This adds adding fix-date information based on first-observed fix information to records for the alpine provider.
Partially implements #742 
- #852
> Add fix date processing for alpine

- src/vunnel/tool/fixdate/first_observed.py
- tests/unit/tool/test_first_observed.py
The fixdater does not have all rows as `collate nocase` which means its up to each query to add this as needed. This adjusts the helper class to add nocase to:
- vuln_id
- provider
- full_cpe
- ecosystem
I don't think fix_version can safely make the same assumption here for case insensitivity.
> Ensure fetching entries from the fixdates db is case insensitive

- src/vunnel/tool/fixdate/first_observed.py
- tests/unit/tool/test_first_observed.py
The underlying tables now have collate nocase for most columns now, thus the query can be simplified (this makes no functional change).
> Add nocase statements to schema (remove from queries)

- src/vunnel/providers/nvd/manager.py
- tests/unit/providers/nvd/test_manager.py
There is one path in the NVD provider where the fix dates are applied but not overrides, this PR addresses this behavior.
Fixes https://github.com/anchore/grype-db/issues/681
> Apply fix dates and overrides together
